version: "3.0"
services:
  db:
    container_name: "db_quiz"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_quiz_data:/var/lib/postgresql/data

volumes:
  db_quiz_data:
